#!/usr/bin/env bash
#@author: jakeyap on 20201013 1130pm

#conda activate env1
# exp12
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0,1,4,5,6 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --WEIGHTED_STANCE --MODELNAME='ModelB4' --NAME='exp12' --DO_TRAIN
# exp13
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0,1,4,5,6 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --WEIGHTED_STANCE --MODELNAME='ModelB3' --NAME='exp13' --DO_TRAIN
# exp14
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0,1,4,5,6 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --WEIGHTED_STANCE --MODELNAME='ModelB2' --NAME='exp14' --DO_TRAIN
# exp15
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0,1,4,5,6 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --WEIGHTED_STANCE --MODELNAME='ModelB1' --NAME='exp15' --DO_TRAIN
# exp16
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0,1,4,5,6 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --BATCH_SIZE_TEST=25 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='ModelB4' --NAME='exp16' --DO_TRAIN
# exp17
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0,1,4,5,6 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --BATCH_SIZE_TEST=25 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='ModelB3' --NAME='exp17' --DO_TRAIN
# exp18
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0,1,4,5,6 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --BATCH_SIZE_TEST=25 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='ModelB2' --NAME='exp18' --DO_TRAIN
# exp20
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=5,7 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=6 --BATCH_SIZE_TEST=6 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='ModelC4' --NAME='exp20' --DO_TRAIN --WEIGHTED_STANCE
# exp21
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=5,7 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=6 --BATCH_SIZE_TEST=6 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='ModelC3' --NAME='exp21' --DO_TRAIN --WEIGHTED_STANCE
# exp22
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=4,5,6,7 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=12 --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='ModelC2' --NAME='exp22' --DO_TRAIN --WEIGHTED_STANCE
# exp23
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=4,5,6,7 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=12 --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='ModelC1' --NAME='exp23' --DO_TRAIN --WEIGHTED_STANCE

# exp28
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,4,5,7 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=12 --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='ModelB4' --NAME='exp28' --DO_TRAIN --WEIGHTED_STANCE --DOUBLESTEP
# exp29
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,4,5,7 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=12 --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='ModelB3' --NAME='exp29' --DO_TRAIN --WEIGHTED_STANCE --DOUBLESTEP
# exp30
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,4,5,7 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=12 --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='ModelB2' --NAME='exp30' --DO_TRAIN --WEIGHTED_STANCE --DOUBLESTEP