#!/usr/bin/env bash
#@author: jakeyap on 20201014 3:00pm

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0,1,2,3,4 python main.py --N_EPOCHS=2 --BATCH_SIZE_TRAIN=25 --LOG_INTERVAL=1 --LEARNING_RATE=0.00005 --MOMENTUM=0.125 --OPTIMIZER='SGD' --DEBUG --WEIGHTED_STANCE

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0,1,2,3,4 python main.py --N_EPOCHS=2 --BATCH_SIZE_TRAIN=25 --LOG_INTERVAL=1 --LEARNING_RATE=0.00005 --MOMENTUM=0.125 --OPTIMIZER='ADAM' --DEBUG --WEIGHTED_STANCE

#!/usr/bin/env bash
#@author: jakeyap on 20201013 1130pm

#conda activate env1
# exp4
# PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=25 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=1 --LEARNING_RATE=0.00005 --OPTIMIZER='ADAM' --MODELNAME='ModelA0' --NAME='exp4'

# exp6
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=25 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10 --LEARNING_RATE=0.00020 --OPTIMIZER='ADAM' --MODELNAME='ModelA0' --NAME='exp6'

# exp7
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=20 --BATCH_SIZE_TRAIN=25 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --WEIGHTED_STANCE --MODELNAME='ModelA0' --NAME='exp7'

# exp8
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=20 --BATCH_SIZE_TRAIN=25 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10 --LEARNING_RATE=0.00002 --OPTIMIZER='ADAM' --WEIGHTED_STANCE --MODELNAME='ModelA0' --NAME='exp8'

# exp9
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=20 --BATCH_SIZE_TRAIN=25 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10 --LEARNING_RATE=0.00005 --OPTIMIZER='ADAM' --WEIGHTED_STANCE --MODELNAME='ModelA0' --NAME='exp9'

# exp10
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=20 --BATCH_SIZE_TRAIN=25 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10 --LEARNING_RATE=0.00010 --OPTIMIZER='ADAM' --WEIGHTED_STANCE --MODELNAME='ModelA0' --NAME='exp10'

# exp11
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=20 --BATCH_SIZE_TRAIN=25 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10 --LEARNING_RATE=0.00020 --OPTIMIZER='ADAM' --WEIGHTED_STANCE --MODELNAME='ModelA0' --NAME='exp11'


# exp12
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --WEIGHTED_STANCE --MODELNAME='ModelB4' --NAME='exp12'

# exp13
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --WEIGHTED_STANCE --MODELNAME='ModelB3' --NAME='exp13'

# exp14
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --WEIGHTED_STANCE --MODELNAME='ModelB2' --NAME='exp14'

# exp15
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --WEIGHTED_STANCE --MODELNAME='ModelB1' --NAME='exp15'

# exp16
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='ModelB4' --NAME='exp16'

# exp17
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='ModelB3' --NAME='exp17'

# exp18
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='ModelB2' --NAME='exp18'

# exp19
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main.py --N_EPOCHS=10 --BATCH_SIZE_TRAIN=15 --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10 --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='ModelB1' --NAME='exp19'