#!/usr/bin/env bash
#@author: jakeyap on 20201025 10:00pm

# ModelA0s
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp4.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp5.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp6.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp7.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp8.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp9.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp10.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp11.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB4_exp12.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB3_exp13.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB2_exp14.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB1_exp15.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB4_exp16.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB3_exp17.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB2_exp18.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB1_exp19.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=5,7 python tests_on_srq.py --MODELFILE='ModelC4_exp20.bin' --BATCH_SIZE_TEST=6 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=5,7 python tests_on_srq.py --MODELFILE='ModelC3_exp21.bin' --BATCH_SIZE_TEST=6 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=5,7 python tests_on_srq.py --MODELFILE='ModelC2_exp22.bin' --BATCH_SIZE_TEST=6 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=5,7 python tests_on_srq.py --MODELFILE='ModelC1_exp23.bin' --BATCH_SIZE_TEST=6 --LOG_INTERVAL=10

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelC4_exp24.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelC3_exp25.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelC2_exp26.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelC1_exp27.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
### ABOVE NOT DONE ON PREDICT
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelB4_exp28.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelB3_exp29.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelB2_exp30.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD4_exp35.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=4 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD3_exp32.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=4 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD2_exp33.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=4 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD1_exp34.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=4 --LOG_INTERVAL=10

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD4_exp39.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD3_exp40.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD2_exp41.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD1_exp42.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD4_exp31.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD3_exp36.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD2_exp37.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD1_exp38.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD4_exp43.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=24 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD3_exp44.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=24 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD2_exp45.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=24 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD1_exp46.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=24 --LOG_INTERVAL=10

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD1_exp47.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=24 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelD2_exp48.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=24 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelE2_exp49.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=48 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelE1_exp50.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=48 --LOG_INTERVAL=10

PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelE2_exp51.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=48 --LOG_INTERVAL=10
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelE1_exp52.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=48 --LOG_INTERVAL=10
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelE4_exp53.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=48 --LOG_INTERVAL=10
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelE3_exp54.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=48 --LOG_INTERVAL=10
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelE4_exp55.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=48 --LOG_INTERVAL=10
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelE3_exp56.bin' --STANCE_NUM_LABELS=11 --BATCH_SIZE_TEST=48 --LOG_INTERVAL=10
