#!/usr/bin/env bash
#@author: jakeyap on 20201013 1130pm

# exp40
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
    --OPTIMIZER='ADAM' --DO_TRAIN  \
    --MODELNAME='alt_ModelF4' --NAME='exp40' \
    --WEIGHTED_STANCE
    
# exp39
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
    --OPTIMIZER='ADAM' --DO_TRAIN  \
    --MODELNAME='alt_ModelF3' --NAME='exp39' \
    --WEIGHTED_STANCE

# exp38
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
    --OPTIMIZER='ADAM' --DO_TRAIN  \
    --MODELNAME='alt_ModelF2' --NAME='exp38' \
    --WEIGHTED_STANCE

# exp37
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
    --OPTIMIZER='ADAM' --DO_TRAIN  \
    --MODELNAME='alt_ModelF1' --NAME='exp37' \
    --WEIGHTED_STANCE

# exp36
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF4' --NAME='exp36' \
#    --WEIGHTED_STANCE
    
# exp35
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF3' --NAME='exp35' \
#    --WEIGHTED_STANCE

# exp34
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF2' --NAME='exp34' \
#    --WEIGHTED_STANCE

# exp33
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF1' --NAME='exp33' \
#    --WEIGHTED_STANCE


# exp32
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelG4' --NAME='exp32' \
#    --WEIGHTED_STANCE

# exp31
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelG3' --NAME='exp31' \
#    --WEIGHTED_STANCE

# exp30
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelG2' --NAME='exp30' \
#    --WEIGHTED_STANCE

# exp29
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelG1' --NAME='exp29' \
#    --WEIGHTED_STANCE

# exp28
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelG4' --NAME='exp28' \
#    --WEIGHTED_STANCE

# exp27
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelG3' --NAME='exp27' \
#    --WEIGHTED_STANCE

# exp26
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelG2' --NAME='exp26' \
#    --WEIGHTED_STANCE

# exp25
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelG1' --NAME='exp25' \
#    --WEIGHTED_STANCE


# exp24
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF4' --NAME='exp24' \
#    --WEIGHTED_STANCE

# exp23
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF3' --NAME='exp23' \
#    --WEIGHTED_STANCE

# exp22
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF2' --NAME='exp22' \
#    --WEIGHTED_STANCE

# exp21
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF1' --NAME='exp21' \
#    --WEIGHTED_STANCE
    
# exp20
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF4' --NAME='exp20' \
#    --WEIGHTED_STANCE
    
# exp19
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF3' --NAME='exp19' \
#    --WEIGHTED_STANCE
        
# exp18
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF2' --NAME='exp18' \
#    --WEIGHTED_STANCE

# exp17
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF1' --NAME='exp17' \
#    --WEIGHTED_STANCE
    
# ========= UNCOMMENT THIS SECTION TOMORROW ========= 
# =========  RMB TO CHANGE WEIGHTS IN CODE  ========= 
# exp16
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF4' --NAME='exp16' \
#    --WEIGHTED_STANCE
    
# exp15
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF3' --NAME='exp15' \
#    --WEIGHTED_STANCE
        
# exp14
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF2' --NAME='exp14' \
#    --WEIGHTED_STANCE

# exp13
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF1' --NAME='exp13' \
#    --WEIGHTED_STANCE
# =========     END OF UNCOMMENT SECTION    ========= 

# exp12
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF4' --NAME='exp12' \
#    --WEIGHTED_STANCE

# exp11
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF3' --NAME='exp11' \
#    --WEIGHTED_STANCE

# exp10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF2' --NAME='exp10' \
#    --WEIGHTED_STANCE

# exp09
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=20 --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF1' --NAME='exp09' \
#    --WEIGHTED_STANCE


# exp08
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=8 --BATCH_SIZE_TEST=8 --LOG_INTERVAL=10 --N_EPOCHS=10 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=256 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF4' --NAME='exp08' \
#    --WEIGHTED_STANCE
    
# exp07
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=8 --BATCH_SIZE_TEST=8 --LOG_INTERVAL=10 --N_EPOCHS=10 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=256 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF3' --NAME='exp07' \
#    --WEIGHTED_STANCE
        
# exp06
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=8 --BATCH_SIZE_TEST=8 --LOG_INTERVAL=10 --N_EPOCHS=10 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=256 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF2' --NAME='exp06' \
#    --WEIGHTED_STANCE

# exp05
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=8 --BATCH_SIZE_TEST=8 --LOG_INTERVAL=10 --N_EPOCHS=10 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=256 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF1' --NAME='exp05' \
#    --WEIGHTED_STANCE



# exp04
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=8 --BATCH_SIZE_TEST=8 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=256 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF4' --NAME='exp04' \
#    --WEIGHTED_STANCE
    
# exp03
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=8 --BATCH_SIZE_TEST=8 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=256 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF3' --NAME='exp03' \
#    --WEIGHTED_STANCE
        
# exp02
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=8 --BATCH_SIZE_TEST=8 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=256 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF2' --NAME='exp02' \
#    --WEIGHTED_STANCE

# exp01
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=8 --BATCH_SIZE_TEST=8 --LOG_INTERVAL=10 --N_EPOCHS=8 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=256 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF1' --NAME='exp01' \
#    --WEIGHTED_STANCE
    
