#!/usr/bin/env bash
#@author: jakeyap on 20201025 10:00pm

# ModelA0s
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp4.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp5.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp6.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp7.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp8.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp9.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp10.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelA0_exp11.bin' --BATCH_SIZE_TEST=20 --LOG_INTERVAL=10

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB4_exp12.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB3_exp13.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB2_exp14.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB1_exp15.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB4_exp16.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB3_exp17.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB2_exp18.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3,5,6,7 python tests_on_srq.py --MODELFILE='ModelB1_exp19.bin' --BATCH_SIZE_TEST=12 --LOG_INTERVAL=10

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=5,7 python tests_on_srq.py --MODELFILE='ModelC4_exp20.bin' --BATCH_SIZE_TEST=6 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=5,7 python tests_on_srq.py --MODELFILE='ModelC3_exp21.bin' --BATCH_SIZE_TEST=6 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=5,7 python tests_on_srq.py --MODELFILE='ModelC2_exp22.bin' --BATCH_SIZE_TEST=6 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=5,7 python tests_on_srq.py --MODELFILE='ModelC1_exp23.bin' --BATCH_SIZE_TEST=6 --LOG_INTERVAL=10

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelC4_exp24.bin' --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelC3_exp25.bin' --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelC2_exp26.bin' --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq.py --MODELFILE='ModelC1_exp27.bin' --BATCH_SIZE_TEST=2 --LOG_INTERVAL=10