#!/usr/bin/env bash
#@author: jakeyap on 20201025 10:00pm

# this is to train a mapping layer from 10 Coase Discourse classes to 4 SDQC classes
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq_addon.py --MODELFILE='alt_ModelG3_exp31.bin' \
#    --BATCH_SIZE_TRAIN=2 --BATCH_SIZE_TEST=96 --N_EPOCHS=10 --LEARNING_RATE=0.0005 \
#    --MAX_POST_LENGTH=256 --MAX_POST_PER_THREAD=7 --MAP_OPTION=2 --LOG_INTERVAL=1 --DO_TRAIN

# exp01
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF1_exp01.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01

# exp02    
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF2_exp02.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01

# exp03
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF3_exp03.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01
    
# exp04
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF4_exp04.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01
    
# exp05
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF1_exp05.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01

# exp06    
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF2_exp06.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01

# exp07
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF3_exp07.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01
    
# exp08
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF4_exp08.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01
    
# exp09
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF1_exp09.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01

# exp10    
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF2_exp10.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01

# exp11
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF3_exp11.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01
    
# exp12
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF4_exp12.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01
    
# exp13
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF1_exp13.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01

# exp14
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF2_exp14.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01

# exp15
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF3_exp15.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01
    
# exp16
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF4_exp16.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01
    
# exp17
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF1_exp17.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01

# exp18    
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF2_exp18.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01

# exp19
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF3_exp19.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01
    
# exp20
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF4_exp20.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01
    
# exp21
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF1_exp21.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01

# exp22 
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF2_exp22.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01

# exp23
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF3_exp23.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01
    
# exp24
PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=3 python tests_on_srq_addon.py --MODELFILE='alt_ModelF4_exp24.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=20 --LEARNING_RATE=0.01
    
