#!/usr/bin/env bash
#@author: jakeyap on 20201014 3:00pm

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0,1,2,3,4 python main.py --N_EPOCHS=2 --BATCH_SIZE_TRAIN=25 --LOG_INTERVAL=1 --LEARNING_RATE=0.00005 --MOMENTUM=0.125 --OPTIMIZER='SGD' --DEBUG --WEIGHTED_STANCE

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0,1,2,3,4 python main.py --N_EPOCHS=2 --BATCH_SIZE_TRAIN=25 --LOG_INTERVAL=1 --LEARNING_RATE=0.00005 --MOMENTUM=0.125 --OPTIMIZER='ADAM' --DEBUG --WEIGHTED_STANCE

#!/usr/bin/env bash
#@author: jakeyap on 20201013 1130pm

#conda activate env1

PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python tests_on_srq_addon.py --MODELFILE='alt_ModelF2_exp14.bin' --DO_TRAIN --MAP_OPTION=2 \
    --BATCH_SIZE_TRAIN=128 --BATCH_SIZE_TEST=128 --MAX_POST_LENGTH=128 --MAX_POST_PER_THREAD=7 --N_EPOCHS=20 --LOG_INTERVAL=1 --TRAIN_PCT=60 --LEARNING_RATE=0.01

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main_appr3.py --N_EPOCHS=2 \
#    --BATCH_SIZE_TRAIN=1 --BATCH_SIZE_TEST=4 --LOG_INTERVAL=1 --MAX_POST_LEN=512 \
#    --LEARNING_RATE=0.00001 --OPTIMIZER='ADAM' --MODELNAME='alt_ModelF1' \
#    --NAME='test' --DEBUG --WEIGHTED_STANCE --THREAD_LENGTH_DIVIDER=8 \
#    --STRIDES=2 --DO_TRAIN

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=1 --BATCH_SIZE_TEST=8 --LOG_INTERVAL=1 --N_EPOCHS=1 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF4' --NAME='test' --DEBUG
#    --WEIGHTED_STANCE --DOUBLESTEP

#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=1 --BATCH_SIZE_TEST=8 --LOG_INTERVAL=1 --N_EPOCHS=1 \
#    --LEARNING_RATE=0.00005 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM_V' --DO_TRAIN  \
#    --MODELNAME='alt_ModelF4' --NAME='test' --DEBUG \
#    --WEIGHTED_STANCE
    
#PYTHONIOENCODING=utf-8 CUDA_VISIBLE_DEVICES=0 python main_appr3.py \
#    --BATCH_SIZE_TRAIN=1 --BATCH_SIZE_TEST=8 --LOG_INTERVAL=1 --N_EPOCHS=1 \
#    --LEARNING_RATE=0.00001 --MAX_POST_LENGTH=128 --STRIDES=2 --THREAD_LENGTH_DIVIDER=16 \
#    --OPTIMIZER='ADAM' --DO_TRAIN  \
#    --MODELNAME='alt_ModelG4' --NAME='test' --DEBUG \
#    --WEIGHTED_STANCE